1. If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [34]:
def sum_even():
    multiples = []
    even_sum = 0
    for i in range(1000):
        if i % 3 == 0 or i % 5 == 0:
            even_sum += i
    return even_sum
print(sum_even())

233168

2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [69]:
def fib_finder():
    a = 1
    b = 2
    sum = 0

while b <= 4000000:
    if b % 2 == 0:
        sum += b
    c = a + b
    a = b
    b = c

print(sum)

4613732

3. The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [66]:
n = 600851475143
i = 2

while i * i <= n:
    while n % i == 0:
        n //= i
    i += 1

if n > 1:
    print(n)
else:
    print(i - 1)

6857

4. A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [65]:
largest_palindrome = 0

for i in range(100, 1000):
    for j in range(100, 1000):
        product = i * j
        if str(product) == str(product)[::-1]:
            largest_palindrome = max(largest_palindrome, product)

print(largest_palindrome)

906609

5. 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

6. The sum of the squares of the first ten natural numbers is, 1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is, (1 + 2 + ... + 10)^2 = 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is, 3025 - 385 = 2640

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [83]:
def one_hundred_nat():
    for i in range(1,10):
        return i == (10(10+1)(2*10+1))/6
print(i)

1472

<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_1140/3622915206.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  return i == (10(10+1)(2*10+1))/6

7. By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10001st prime number?

In [75]:
def prime_number():
    numbers = range(10002)
    for num in numbers:
        if i == numbers[::-1]:
            print(i)
result = prime_number()
print(result)

None

8. A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a^2 + b^2 = c^2

For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [64]:
def pit_trip():
    for i in range(1, 1000):
        for j in range(i+1, 1000):
            h = (i**2 + j**2)**0.5
            if h.is_integer() and i + j + h == 1000:
                return int(i * j * h)
    return None
result = pit_trip()
print(result)

31875000

9. The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [78]:
def nth_prime(n):
    primes = []
    count = 0
    i = 2
    while True:
        is_prime = True
        for p in primes:
            if i % p == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(i)
            count += 1
            if count == n:
                return i
        i += 1
result = nth_prime(10001)
print(result)  # output: 104743

104743

10. The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?